[package]
name = "bombadil-sandbox-runtime"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
bombadil-ltl = { path = "../vendor/bombadil-ltl" }
bombadil-schema = { path = "../vendor/bombadil-schema" }
stdx = { path = "../vendor/stdx" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
